-- Tailored resumes generated by AI for a specific job + profile.
-- Writes happen server-side via the service-role key, scoped by Clerk user_id.

create table if not exists public.resumes (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  job_id uuid not null references public.jobs (id) on delete cascade,
  resume jsonb not null,
  gap_report jsonb not null,
  talking_points jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists resumes_user_id_created_idx
  on public.resumes (user_id, created_at desc);

create index if not exists resumes_job_id_idx
  on public.resumes (job_id);

alter table public.resumes enable row level security;
-- Только service-role пишет/читает; anon/auth заблокированы.
